apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-vllm
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      seldon.io/runtime: vllm
  podMetricsEndpoints:
    - port: metrics
      path: /prometheus
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_seldon_deployment_id
          targetLabel: seldon_deployment
        - sourceLabels:
            - __meta_kubernetes_pod_label_seldon_io_runtime
          targetLabel: runtime
    - port: vllm-http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_seldon_deployment_id
          targetLabel: seldon_deployment
        - sourceLabels:
            - __meta_kubernetes_pod_label_seldon_io_runtime
          targetLabel: runtime
